spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
        uri: mongodb://mario:example@localhost:27017/tracker?authSource=admin&retryWrites=true&w=majority
        auto-index-creation: true

jwt:
  secret: secret
  expirationTime: 3600





